export const SenateMembers = [
  {
    states: [
      {
        name: "Alabama",
        capital: "Montgomery",
        popSize: "4,934,193",
        flag: "https://hrc-prod-requests.s3-us-west-2.amazonaws.com/images/made/images/remote/http_hrc-assets.s3-website-us-east-1.amazonaws.com/files/images/blog/_1200x630_crop_center-center_none/alabama_flag_blog1600_800_450.png?mtime=20200713144842&focal=none&tmtime=20210423183135",
        S1Name: "Richard Shelby",
        S1Photo:
          "https://pbs.twimg.com/profile_images/621070518834212864/ikIQKvUq_400x400.jpg",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Tommy Tuberville",
        S2Photo:
          "https://upload.wikimedia.org/wikipedia/commons/7/7a/Tommy_Tuberville_117th_Congress_Portrait.jpg",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Alaska",
        capital: "Juneau",
        popSize: "724,357",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Alaska.svg/2560px-Flag_of_Alaska.svg.png",
        S1Name: "Lisa Murkowski",
        S1Party: "R",
        S1Photo:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ4CGhXZNLsCB99WPZMog-LGnCuRMYmbZRFQ-B6mdTQB-Dpo2bkMDP0vba6cjLsBW08YU&usqp=CAU",
        S1Social: "N/A",
        S2Name: "Dan Sullivan",
        S2Photo:
          "https://bloximages.newyork1.vip.townnews.com/newsminer.com/content/tncms/assets/v3/editorial/c/46/c4653726-ebb2-11e7-a077-5bf1ac4c18d6/5a44bb9ad3b62.image.jpg",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Arizona",
        capital: "Phoenix",
        popSize: "7,520,103",
        flag: "https://cdn3.volusion.com/mtwsb.danrt/v/vspfiles/photos/SNFALL-2.jpg?v-cache=1557004120",
        S1Name: "Kyrsten Sinema",
        S1Photo:
          "https://kyrstensinema.com/wp-content/uploads/2018/03/Sinema_18_sq-1.jpg",
        S1Social: "N/A",
        S1Party: "D",
        S2Name: "Mark Kelly",
        S2Photo:
          "https://lh3.googleusercontent.com/proxy/CPJoHPjqPLdyUFS77JITI7qu5c8k-IorQ0jk-9KpbRZpo8FftBdogtxIl6G1YDl0Qs0fbRS5s3hMdnn7ajntxVctN6L8pXevQmMfaUv3CSrEKA1cOiGcaayJllwHm6y10bUMoWjnfzFmtZIlhQ",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Arkansas",
        capital: "Little Rock",
        popSize: "3,033,946",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Arkansas.svg/1200px-Flag_of_Arkansas.svg.png",
        S1Name: "John Boozman",
        S1Photo:
          "https://upload.wikimedia.org/wikipedia/commons/3/30/Senator_John_Boozman_Official_Portrait_%28115th_Congress%29.jpg",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Tom Cotton",
        S2Photo:
          "https://upload.wikimedia.org/wikipedia/commons/4/49/Tom_Cotton_official_Senate_photo.jpg",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "California",
        capital: "Sacramento",
        popSize: "39,613,493",
        flag: "https://cdn.britannica.com/46/7046-004-BB1F8E32/state-flag-Bear-Flag-California-red-star-July-9-1846.jpg",
        S1Name: "Dianne Feinstein",
        S1Photo:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Dianne_Feinstein%2C_official_Senate_photo_%28cropped%29.jpg/373px-Dianne_Feinstein%2C_official_Senate_photo_%28cropped%29.jpg",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Alex Padilla",
        S2Photo:
          "https://bpr.berkeley.edu/wp-content/uploads/2021/03/alex-padilla.jpg",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Colorado",
        capital: "Denver",
        popSize: "5,893,634",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Flag_of_Colorado.svg/640px-Flag_of_Colorado.svg.png",
        S1Name: "Michael Bennet",
        S1Photo:
          "https://upload.wikimedia.org/wikipedia/commons/f/fc/Michael_Bennet_Official_Photo.jpg",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "John Hickenlooper",
        S2Photo:
          "https://upload.wikimedia.org/wikipedia/commons/a/a8/John_Hickenlooper%2C_official_portrait%2C_117th_Congress.jpeg",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Connecticut",
        capital: "Hartford",
        popSize: "3,552,821",
        flag: "https://cdn.britannica.com/69/7769-004-989D0811/flags-Connecticut-state-flag-design-arms-coat-1897.jpg",
        S1Name: "Richard Blumenthal",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Chris Murphy",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Delaware",
        capital: "Dover",
        popSize: "990,334",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Flag_of_Delaware.svg/1200px-Flag_of_Delaware.svg.png",
        S1Name: "Tom Carper",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Chris Coons",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Florida",
        capital: "Tallahassee",
        popSize: "21,944,577",
        flag: "https://libertyflagandbanner.com/wp-content/uploads/2015/08/florida-flag-1.jpg",
        S1Name: "Marco Rubio",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Rick Scott",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Georgia",
        capital: "Atlanta",
        popSize: "3,976,525",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Georgia_%28U.S._state%29.svg/1200px-Flag_of_Georgia_%28U.S._state%29.svg.png",
        S1Name: "Jon Ossoff",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Raphael Warnock",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Hawaii",
        capital: "Honolulu",
        popSize: "1,406,430",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_the_British_East_India_Company_%281801%29.svg/170px-Flag_of_the_British_East_India_Company_%281801%29.svg.png",
        S1Name: "Brian Schatz",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Mazie Hirono",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Idaho",
        capital: "Boise",
        popSize: "1,860,123",
        flag: "https://libertyflagandbanner.com/wp-content/uploads/2015/08/idaho-flag.jpg",
        S1Name: "Mike Crapo",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Jim Risch",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Illinois",
        capital: "Springfield",
        popSize: "12,569,321",
        flag: "https://cdn.britannica.com/94/1494-004-D676DAA0/prizewinner-state-flag-Illinois-design-emblem-competition-1969.jpg",
        S1Name: "Dick Durbin",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "	Tammy Duckworth",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Indiana",
        capital: "Indianapolis",
        popSize: "6,805,663",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Flag_of_Indiana.svg/1200px-Flag_of_Indiana.svg.png",
        S1Name: "Todd Young",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Mike Braun",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Iowa",
        capital: "Des Moines",
        popSize: "3,167,974",
        flag: "https://cdn.britannica.com/19/1719-004-0A33620B/state-flag-necessity-question-Iowa-World-War-1921.jpg",
        S1Name: "Chuck Grassley",
        S1Social: "N/A",
        S2Name: "Joni Ernst",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Kansas",
        capital: "Topeka",
        popSize: "2,917,224",
        flag: "https://cdn.britannica.com/79/1879-004-AE87DA0F/state-flag-Kansas-use-bottom-name-addition-1927.jpg",
        S1Name: "Jerry Moran",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Roger Marshall",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Kentucky",
        capital: "Frankfort",
        popSize: "4,480,713",
        flag: "https://m.media-amazon.com/images/I/71L9BnOj9wL._AC_SL1500_.jpg",
        S1Name: "Mitch McConnell",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Rand Paul",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Louisiana",
        capital: "Baton Rouge",
        popSize: "4,627,002",
        flag: "https://cdn11.bigcommerce.com/s-c0w1eon/images/stencil/1280x1280/products/99/292/LOUISIANA__35262.1454636476.jpg?c=2",
        S1Name: "Bill Cassidy",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "John Kennedy",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Maine",
        capital: "Augusta",
        popSize: "1,354,522",
        flag: "https://cdn.shopify.com/s/files/1/1364/2399/products/maine-state-flag_2048x.jpg?v=1527562942",
        S1Name: "Susan Collins",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Angus King",
        S2Party: "I",
        S2Social: "N/A",
      },
      {
        name: "Maryland",
        capital: "Annapolis",
        popSize: "6,065,436",
        flag: "https://cdn.britannica.com/38/2338-004-AE838B06/flag-Proprietor-state-Maryland-family-arms-Lord-1904.jpg",
        S1Name: "Ben Cardin",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Chris Van Hollen",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Massachusetts",
        capital: "Boston",
        popSize: "6,912,239",
        flag: "https://cdn.britannica.com/45/2345-004-CA9B0D10/flag-pine-tree-Massachusetts-state-field-arms-1971.jpg",
        S1Name: "Elizabeth Warren",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Ed Markey",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Michigan",
        capital: "Lansing",
        flag: "https://cdn.britannica.com/83/2583-004-BDC7442D/coat-of-arms-seal-flag-Michigan-state-1865.jpg",
        S1Name: "Debbie Stabenow",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Gary Peters",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Minnesota",
        capital: "Saint Paul",
        popSize: "9,992,427",
        flag: "https://cdn.britannica.com/98/2598-004-F6564CCC/Minnesota-cost-emblem-flag-circle-revision-manufacturing-1858.jpg",
        S1Name: "Amy Klobuchar",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Tina Smith",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Mississippi",
        capital: "Jackson",
        popSize: "2,966,407",
        flag: "https://dynaimage.cdn.cnn.com/cnn/c_fill,g_auto,w_1200,h_675,ar_16:9/https%3A%2F%2Fcdn.cnn.com%2Fcnnnext%2Fdam%2Fassets%2F200902143307-new-magnolia-flag-mississippi.jpg",
        S1Name: "Roger Wicker",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Cindy Hyde-Smith",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Missouri",
        capital: "Jefferson City",
        popSize: "6,169,038",
        flag: "https://statesymbolsusa.org/sites/statesymbolsusa.org/files/primary-images/flagofmissouristateflag.jpg",
        S1Name: "Roy Blunt",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Josh Hawley",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Montana",
        capital: "Helena",
        popSize: "1,085,004",
        flag: "https://statesymbolsusa.org/sites/statesymbolsusa.org/files/styles/large/public/symbol-place-images/flagofmontanastateflag.jpg?itok=Wc8Qwiwe",
        S1Name: "Jon Tester",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Steve Daines",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Nebraska",
        capital: "Lincoln",
        popSize: "1,951,996",
        flag: "https://cdn.britannica.com/48/2948-004-59603928/state-banner-Nebraska-flag-flags-seal-design-1963.jpg",
        S1Name: "Deb Fischer",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Ben Sasse",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Nevada",
        capital: "Carson City",
        popSize: "3,185,786",
        flag: "https://cdn.britannica.com/86/2986-004-185B6EC4/state-flag-times-Nevada-one-design-contest-1953.jpg",
        S1Name: "Catherine Cortez Masto",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Jacky Rosen",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "New Hampshire",
        capital: "Concord",
        popSize: "1,372,203",
        flag: "https://cdn.britannica.com/96/2996-004-3011C363/Provision-state-flag-New-Hampshire-military-purposes-1931.jpg",
        S1Name: "Jeanne Shaheen",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Maggie Hassan",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "New Jersey",
        capital: "Trenton",
        popSize: "8,874,520",
        flag: "https://cdn.britannica.com/99/2999-004-156FB7EF/state-flag-New-Jersey-George-Washington-field-1779.jpg",
        S1Name: "Bob Menendez",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Cory Booker",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "New Mexico",
        capital: "Santa Fe",
        flag: "https://cdn.britannica.com/03/3003-050-F0EB2D27/flag-New-Mexico-state-flags-one-design-March-15-1925.jpg",
        S1Name: "Martin Heinrich",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Ben Ray Luján",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "New York",
        capital: "Albany",
        flag: "https://cdn.britannica.com/14/3014-050-17B84006/flag-New-York-color-uniforms-facings-American-1909.jpg",
        S1Name: "Chuck Schumer",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Kirsten Gillibrand",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "North Carolina",
        capital: "Raleigh",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Flag_of_North_Carolina.svg/1200px-Flag_of_North_Carolina.svg.png",
        S1Name: "Richard Burr",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Thom Tillis",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "North Dakota",
        capital: "Bismarck",
        flag: "https://cdn.britannica.com/88/3088-004-E8605DCF/flag-North-Dakota-National-Guard-change-state-1911.jpg",
        S1Name: "John Hoeven",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Kevin Cramer",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Ohio",
        capital: "Columbus",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Ohio.svg/1200px-Flag_of_Ohio.svg.png",
        S1Name: "Sherrod Brown",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Rob Portman",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Oklahoma",
        capital: "Oklahoma City",
        flag: "https://cdn.britannica.com/14/3214-004-BEE9E2B9/star-flag-field-Oklahoma-contest-color-sky-1941.jpg",
        S1Name: "Jim Inhofe",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "James Lankford",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Oregon",
        capital: "Salem",
        flag: "https://cdn.britannica.com/57/3257-004-050DB90C/state-flag-Oregon-distinction-escutcheon-gold-field-1859.jpg",
        S1Name: "Ron Wyden",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Jeff Merkley",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Pennsylvania",
        capital: "Harrisburg",
        flag: "https://cdn.britannica.com/29/3429-004-4A64B1C5/Pennsylvania-state-flag-William-Penn-blue-coat-1777.jpg",
        S1Name: "Bob Casey Jr.",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Pat Toomey",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Rhode Island",
        capital: "Providence",
        flag: "https://cdn3.volusion.com/mtwsb.danrt/v/vspfiles/photos/STRIN-2.jpg?v-cache=1525220409",
        S1Name: "Jack Reed",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Sheldon Whitehouse",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "South Carolina",
        capital: "Columbia",
        flag: "https://cdn.britannica.com/14/4314-004-A1CFEB4A/state-flag-South-Carolina-Union-fort-palmetto-1861.jpg",
        S1Name: "Lindsey Graham",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Tim Scott",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "South Dakota",
        capital: "Pierre",
        flag: "https://static.grainger.com/rp/s/is/image/Grainger/2NEN5_AL01",
        S1Name: "John Thune",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Mike Rounds",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Tennessee",
        capital: "Nashville",
        flag: "https://cdn.britannica.com/42/4642-004-4871942A/flag-state-Tennessee-Centennial-Exposition-presidents-captain-1905.jpg",
        S1Name: "Marsha Blackburn",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Bill Hagerty",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Texas",
        capital: "Austin",
        flag: "https://cdn.britannica.com/51/4651-050-4F35C6CB/flags-Texas-independence-motif-flag-Mexico-star-1845.jpg",
        S1Name: "John Cornyn",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Ted Cruz",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Utah",
        capital: "Salt Lake City",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Utah.svg",
        S1Name: "Mike Lee",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Mitt Romney",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Vermont",
        capital: "Montpelier",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Vermont.svg/1200px-Flag_of_Vermont.svg.png",
        S1Name: "Patrick Leahy",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Bernie Sanders",
        S2Party: "I",
        S2Social: "N/A",
      },
      {
        name: "Virginia",
        capital: "Richmond",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Virginia.svg",
        S1Name: "Mark Warner",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Tim Kaine",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Washington",
        capital: "Olympia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Flag_of_Washington.svg/1200px-Flag_of_Washington.svg.png",
        S1Name: "Patty Murray",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Maria Cantwell",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "West Virginia",
        capital: "Charleston",
        flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Flag_of_West_Virginia.svg/1200px-Flag_of_West_Virginia.svg.png",
        S1Name: "Joe Manchin",
        S1Party: "D",
        S1Social: "N/A",
        S2Name: "Shelley Moore Capito",
        S2Party: "R",
        S2Social: "N/A",
      },
      {
        name: "Wisconsin",
        capital: "Madison",
        flag: "https://libertyflagandbanner.com/wp-content/uploads/2015/08/wisconsin-flag.jpg",
        S1Name: "Ron Johnson",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Tammy Baldwin",
        S2Party: "D",
        S2Social: "N/A",
      },
      {
        name: "Wyoming",
        capital: "Cheyenne",
        flag: "https://cdn.britannica.com/38/5238-004-C070D1F2/flag-citizen-Wyoming-response-contest-field-border-1917.jpg",
        S1Name: "John Barrasso",
        S1Party: "R",
        S1Social: "N/A",
        S2Name: "Cynthia Lummis",
        S2Party: "R",
        S2Social: "N/A",
      },
    ],
  },
];
